FROM cgr.dev/chainguard/rust:latest-dev
WORKDIR /app

USER root
RUN apk add --no-cache sqlite-dev
USER nonroot

RUN cargo install cargo-watch --locked

ENTRYPOINT ["cargo"]
CMD ["watch", "-x", "run -p server"]
