FROM cgr.dev/chainguard/rust:latest-dev AS server-build
WORKDIR /app

USER root
RUN apk add --no-cache sqlite-dev

COPY Cargo.toml Cargo.lock ./
COPY server/Cargo.toml ./server/Cargo.toml
COPY server/src ./server/src
RUN cargo build --release --manifest-path server/Cargo.toml

FROM cgr.dev/chainguard/glibc-dynamic:latest
WORKDIR /app

COPY --from=server-build /app/target/release/server /app/server

ENV PORT=43127
EXPOSE 43127

ENTRYPOINT ["/app/server"]
